import { applyDeductions, formatMoney, startOfWeek } from "@/lib/trackuber/calc";
import type { Deduction } from "@/lib/trackuber/types";

export interface FleetDriver {
  id: string;
  code: string;
  name: string;
  email: string;
  app_fee_override: number | null;
}

export interface FleetEntry {
  id?: string;
  driver_id: string;
  date: string;
  gross: number;
  cash: number;
  gas_card: number;
  created_at?: string;
  updated_at?: string;
}

export interface DriverRow {
  driver: FleetDriver;
  gross: number;
  cash: number;
  gasCard: number;
  vat: number;
  appFee: number;
  weeks: number;
  payout: number;
}

export function initialsOf(companyName: string): string {
  const words = companyName.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return "RT";
  if (words.length === 1) return words[0]!.slice(0, 1).toUpperCase();
  return words.map((w) => w[0]!.toUpperCase()).join("");
}

export function nextDriverCode(companyName: string, existingCodes: string[]): string {
  const prefix = initialsOf(companyName);
  let max = 0;
  for (const c of existingCodes) {
    const m = c.match(/(\d+)$/);
    if (c.toUpperCase().startsWith(prefix) && m) max = Math.max(max, parseInt(m[1]!, 10));
  }
  return `${prefix}${String(max + 1).padStart(3, "0")}`;
}

/** Number of distinct Monday–Sunday weeks that have at least one entry. */
export function weeksWithEntries(entries: FleetEntry[]): number {
  const set = new Set(entries.map((e) => startOfWeek(e.date, 1)));
  return set.size;
}

export function buildDriverRow(
  driver: FleetDriver,
  entries: FleetEntry[],
  deductions: Deduction[],
  weeklyAppFee: number,
): DriverRow {
  const mine = entries.filter((e) => e.driver_id === driver.id);
  const gross = mine.reduce((s, e) => s + Number(e.gross || 0), 0);
  const cash = mine.reduce((s, e) => s + Number(e.cash || 0), 0);
  const gasCard = mine.reduce((s, e) => s + Number(e.gas_card || 0), 0);
  const vat = applyDeductions(gross, deductions).total;
  const weeks = weeksWithEntries(mine);
  const fee = driver.app_fee_override ?? weeklyAppFee;
  const appFee = weeks * Number(fee || 0);
  return {
    driver,
    gross,
    cash,
    gasCard,
    vat,
    appFee,
    weeks,
    payout: gross - appFee - cash - vat - gasCard,
  };
}

export function invoiceHtml(
  row: DriverRow,
  opts: { company: string; from: string; to: string; currency: string },
): string {
  const { company, from, to, currency } = opts;
  const money = (n: number) => formatMoney(n, currency);
  const amount = (n: number, prefix = "") => (n ? `${prefix}${money(n)}` : "–");
  const line = (label: string, value: string, strong = false) =>
    `<tr><td style="padding:8px 0;color:${strong ? "#0f172a" : "#475569"};font-weight:${strong ? 600 : 400}">${label}</td>
     <td style="padding:8px 0;text-align:right;font-weight:${strong ? 700 : 500};color:#0f172a">${value}</td></tr>`;

  return `<!doctype html><html><head><meta charset="utf-8"/>
<title>Invoice ${row.driver.code} ${from} to ${to}</title>
<style>
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#0f172a;padding:32px;max-width:720px;margin:0 auto}
h1{font-size:20px;margin:0}
.muted{color:#64748b;font-size:12px}
.box{border:1px solid #e2e8f0;border-radius:14px;padding:20px;margin-top:20px}
table{width:100%;border-collapse:collapse;font-size:14px}
.total{border-top:2px solid #0f172a;margin-top:8px}
@media print{body{padding:12px}}
</style></head><body>
<div style="display:flex;justify-content:space-between;align-items:flex-start">
  <div><h1>${escapeHtml(company)}</h1><div class="muted">Driver settlement invoice</div></div>
  <div style="text-align:right" class="muted">Period<br/><strong style="color:#0f172a">${from} → ${to}</strong></div>
</div>
<div class="box">
  <div style="font-weight:600">${escapeHtml(row.driver.name)}</div>
  <div class="muted">${escapeHtml(row.driver.code)} · ${escapeHtml(row.driver.email)}</div>
</div>
<div class="box">
  <table>
    ${line("Gross earnings", amount(row.gross))}
    ${line("Cash collected", amount(row.cash, "− "))}
    ${line("VAT / fleet commission", amount(row.vat, "− "))}
    ${line(`Application fee (${row.weeks} week${row.weeks === 1 ? "" : "s"})`, amount(row.appFee, "− "))}
    ${line("Gas card", amount(row.gasCard, "− "))}
  </table>
  <div class="total"></div>
  <table>${line("Payout", amount(row.payout), true)}</table>
</div>
<p class="muted">Generated by ${escapeHtml(company)} via RideTracks.</p>
</body></html>`;
}

export function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string,
  );
}

/** Renders HTML in a hidden iframe and opens the print dialog (Save as PDF). */
export function printHtml(html: string, fallbackName: string) {
  try {
    const iframe = document.createElement("iframe");
    iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0";
    document.body.appendChild(iframe);
    const doc = iframe.contentDocument;
    if (!doc || !iframe.contentWindow) throw new Error("no iframe document");
    doc.open();
    doc.write(html);
    doc.close();
    const win = iframe.contentWindow;
    const run = () => {
      try {
        win.focus();
        win.print();
      } catch {
        downloadHtml(html, fallbackName);
      }
      setTimeout(() => iframe.remove(), 1500);
    };
    if (doc.readyState === "complete") setTimeout(run, 150);
    else iframe.onload = () => setTimeout(run, 150);
  } catch {
    downloadHtml(html, fallbackName);
  }
}

export function downloadHtml(html: string, filename: string) {
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
